default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: market_ant_development

test:
  <<: *default
  database: market_ant_test

production:
  <<: *default
  database: market_ant_production
  username: market_ant
  password: <%= ENV['MARKET_ANT_DATABASE_PASSWORD'] %>
